# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-09-25 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_filename', models.CharField(max_length=255)),
                ('breed', models.CharField(blank=True, default='', max_length=255)),
                ('age', models.IntegerField(default=None, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('size', models.CharField(max_length=255)),
            ],
        ),
    ]
