# Generated by Django 2.1.5 on 2019-10-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0006_auto_20191002_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'liked'), ('d', 'disliked')], max_length=1, null=True),
        ),
    ]
